/* =============================================================== *\

	CHINOIS SIMPLIFIÉ - Trad by Miao

\* =============================================================== */

var translateObj =  {
	code:'CN',
	name:'Chinese',
	trad:{
		txt:{
			/* http://library.princeton.edu/departments/tsd/katmandu/reference/months.html */
			m1:'一月', m2:'二月', m3:'三月', m4:'四月', m5:'五月', m6:'六月', m7:'七月', m8:'八月', m9:'九月', m10:'十月', m11:'十一月', m12:'十二月',
			tS1:'秒', tS2:'秒', tM1:'分', tM2:'分', tH1:'小时', tH2:'小时', tJ1:'天', tJ2:'天', 
			ago:'<time>前',
			useHeadphones:"请带上耳机获得最佳体验",
			selectVersion:"请选择一个版本开始进行混音创作",
			enjoyVersion:"体验其它混音版本!",
			tuto1:"拖动装饰物至人物身上开始制作音乐",
			tuto2:"向下拖动人物图标停止音乐",
			tuto3:"点击人物图标开启静音",
			tuto4:"长按人物图标开启独奏模式",
			tuto5:"找到正确的音乐节奏组合即可解锁动画奖励",
			tuto5Title:"解锁奖励",
			mixlistEmpty:"你的音乐库里还未有任何添加，快来创作你的第一首混音作品吧!",
			mixlistInfo:"你的混音曲库每<time>分钟更新一次",
			mixlistBestDj:"全球获得最高票数DJ排行榜。<br>你还没有在榜单里?赶快来分享你的混音吧!",
			mixlistNoCo:"未连接到网络。你的曲库将会在下次连接时更新",
			top50Info:"你刚投过票，但是票数没有增加?别担心，Top 50榜单每小时更新一次 &#128521;",
			replayTitle:"重播模式",
			replayText:"你的混音听起来不错?快来保存并分享吧!",
			randomTitle:"自动模式",
			randomText:"软件自动播放，跟着节奏High起来!",
			copyright:"游戏开发商 SO FAR SO GOOD<br><span>版权所有 © 版权 2018</span>",
			team:"<div class='box-team'>Allan Durand<br>Romain Delambily<br>Incredible Polo</div><div class='box-team'>总监，程序 & 动画<br>设计 & 绘画<br>音乐 & 音效设计</div>",
			stayTuned:"关注我们!",
			visitShop:"访问商店!",
			notShared:'还未分享',
			offline:'离线',
			createdBy:'创建人<name>',
			dedicatedTo:'献给<name>',
			inputName:"你的DJ名*",
			inputTitle:"你的作品名称*",
			inputSearch:"搜索混音作品",
			language:'语言',
			comments:'评价',
			thanks:'谢谢! ',
			result:'<number>条结果',
			results:'<number>条结果'
		},
		pop:{
	  		alreadyVotedTitle:"Hi 各位玩家!",
	  		alreadyVotedText:"你已进行过投票，每位玩家只能投票一次 &#128523;",
	  		noNetworkTitle:"未连接",
	  		noNetworkText:"网络未连接，请重新尝试",
	  		noNetworkVotedText:"你未连接到网络，无法进行投票",
	  		noCoShareText:"你未连接到网络无法进行音乐分享",
	  		noCoShareText2:"你的混音作品已经保存到音乐库里，稍后可以进行分享",
	  		majTitle:"&#128512;",// https://unicode.org/emoji/charts/full-emoji-list.html + http://www.online-toolz.com/tools/unicode-html-entities-convertor.php
	  		majText:"各位玩家好消息! Incredibox最新版本已经在商店等着你咯!",
	  		rateTitle:"&#9733; &#9733; &#9733; &#9733; &#9734;",
	  		rateText:"喜欢Incredibox吗?那来给我5星评分吧，<br>你也可以在应用商店里给我赞美点评哦!",
			dragDropTitle:"滑动-拖放",
			dragDropText:"拖动装饰物至人物身上开始进行录制",
			toShortTitle:"时间太短",
			toShortText:"你的混音作品需要至少录制<minimum-time>秒",
			bonusPlayingTitle:"动画奖励播放中",
			bonusPlayingText:"音乐动画播放时无法进行录制",
			recOkTitle:"混音结束",
			formTitle:"保存你的混音作品",
			shareTitle:"作品已保存",
			shareText:"你的混音作品已经保存到音乐库里，<br>开始分享并跻身Top 50排行榜!",
			bugFunctionTitle:"Function bug",
			bugFunctionText:"对不起，你的浏览器不支持此项功能 &laquo; <function> &raquo;。游戏可能无法正常运行",
	  		notFoundTitle:"未找到混音作品",
	  		notFoundText:"哎呀! 我们暂时无法访问你的混音作品",
	  		deleteBugText:"哎呀! 我们暂时无法删除你的混音作品",
	  		sharingBugTitle:"连接失败",
	  		sharingBugText:"对不起，暂时无法连接到服务器",
	  		deleteTitle:"删除",
	  		deleteText:"你确定要删除此混音作品吗?",
	  		recoverMixTitle:"恢复你的混音作品",
	  		recoverMixText:"这首混音作品是你的，但是在你的设备上不可用了。你想要恢复吗?",
	  		shareSubject:"在Incredibox上欣赏我的混音作品!",
	  		sharePresentMix:"<name>向你介绍他的混音作品« <title> »",
	  		shareTextLike:"如果你喜欢这首混音那就投它一票吧，帮助它进入Incredibox Top 50排行榜",
	  		shareTextBeCool:"来吧，在Incredibox上为我的混音作品投票!",
	  		shareClipboard:"你的混音连接已经复制到剪贴板!",
	  		infoTitle:"提示"
		},
		dial:{
			bluetoothLatencyTitle:"蓝牙Bug",
			bluetoothLatencyText:"对不起，由于音频故障，我们必须要断开你的蓝牙连接"
		},
		bt:{
			version:'版本',
			mixList:'音乐库',
			myMix:'我的混音曲库',
			top50:'Top 50',
			bestDj:'最佳DJ',
			latest:'直播',
			search:'搜索',
			djname:'DJ名',
			mixtitle:'混音作品名称',
			week:'周排行榜',
			month:'月排行榜',
			all:'全部排行榜',
			yes:'是',
			ok:'Ok',
			sure:'确定',
			no:'否',
			nope:'不',
			later:'稍后',
			update:'更新',
			retry:'重试',
			replay:'重播',
			create:'创建混音',
			share:'分享',
			save:'保存',
			tuto:'帮助',
			param:'设置',
			credit:'开发团队',
			info:'提示',
			cancel:'取消',
			more:'更多',
			follow:'关注我们',
			git:'保持联系',
			rate:"软件评分",
			contact:'联系我们'
		}
	}
};